export enum QueryKey {
    dashboardStat,
    dashboardSales,
    dashboardProduct,
    userInfo,
    product,
    Cart,
    productDetail,
    productCategory,
    productCategoryDropdownList,
    transaction,
    transactionDetail,
    shipment,
    shipmentDetail,
}